hb_swagger_ui_default:
  path:     /
  defaults: { _controller: HBSwaggerUiBundle:Docs:index}
  methods: [GET]

hb_swagger_ui_private:
  path:     /private
  defaults: { _controller: HBSwaggerUiBundle:Docs:indexPrivate}
  methods: [GET]

hb_swagger_ui_compta:
  path:     /compta
  defaults: { _controller: HBSwaggerUiBundle:Docs:indexCompta}
  methods: [GET]

hb_swagger_ui_access:
  path:     /access
  defaults: { _controller: HBSwaggerUiBundle:Docs:indexAccess}
  methods: [GET]

hb_swagger_ui_swagger_file:
  path:     /file/{fileName}
  requirements:
    fileName: .+
  defaults: { _controller: HBSwaggerUiBundle:Docs:swaggerFile }
  methods: [GET]

hb_swagger_ui_redirect:
  path:     /{fileName}
  requirements:
    fileName: .+
  defaults: { _controller: HBSwaggerUiBundle:Docs:redirect}
  methods: [GET]
